#!/usr/bin/env bash
# Regenerate docs/MAP.md — annotated module tree.
#
# Walks the Python source tree, pairs each .py with the first non-empty line
# of its module docstring, and tags by directory. Run from repo root or via
# a pre-commit hook. Output is deterministic; safe to commit.
#
# Usage:
#     scripts/gen_map.sh           # writes docs/MAP.md
#     scripts/gen_map.sh --check   # exit 1 if docs/MAP.md is stale

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/docs/MAP.md"
CHECK_ONLY=0
if [[ "${1:-}" == "--check" ]]; then
    CHECK_ONLY=1
fi

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

cd "$ROOT"

{
    echo "# Module map"
    echo
    echo "<!-- Auto-generated by scripts/gen_map.sh. Do not edit by hand. -->"
    echo "<!-- Last regenerated: $(date '+%Y-%m-%d %H:%M:%S %Z') -->"
    echo
    echo "Annotated tree of every Python module in the repo with a one-line"
    echo "summary pulled from each module's docstring (first non-empty line)."
    echo "Run \`scripts/gen_map.sh\` after structural changes."
    echo

    for dir in trading_bot.py load_env.py core strategies brokers infrastructure events servers gui scripts tests rust/src; do
        files=()
        if [[ -f "$dir" ]]; then
            files=("$dir")
        elif [[ -d "$dir" ]]; then
            while IFS= read -r f; do
                files+=("$f")
            done < <(find "$dir" -type f \( -name "*.py" -o -name "*.rs" \) \
                ! -path "*/__pycache__/*" \
                ! -path "*/target/*" \
                | LC_ALL=C sort)
        else
            continue
        fi

        [[ ${#files[@]} -eq 0 ]] && continue

        printf '## `%s`\n\n' "$dir"
        printf '| File | Lines | Description |\n'
        printf '| --- | ---: | --- |\n'
        for f in "${files[@]}"; do
            lines=$(wc -l < "$f" | tr -d ' ')
            desc=""
            case "$f" in
                *.py)
                    desc=$(python3 - <<PY 2>/dev/null || true
import ast, sys
try:
    with open("$f", "r", encoding="utf-8") as fh:
        src = fh.read()
    mod = ast.parse(src)
    doc = ast.get_docstring(mod) or ""
    line = next((ln.strip() for ln in doc.splitlines() if ln.strip()), "")
    print(line[:200])
except Exception:
    pass
PY
)
                    ;;
                *.rs)
                    desc=$(awk '/^\/\/!/ {sub(/^\/\/!\s*/, ""); print; exit}' "$f" | head -c 200)
                    ;;
            esac
            [[ -z "$desc" ]] && desc="(no docstring)"
            printf '| [`%s`](../%s) | %s | %s |\n' "$f" "$f" "$lines" "$desc"
        done
        printf '\n'
    done
} > "$TMP"

if [[ $CHECK_ONLY -eq 1 ]]; then
    # Ignore the auto-generated timestamp line when comparing.
    diff_out=$(diff <(grep -v "Last regenerated" "$OUT" 2>/dev/null) <(grep -v "Last regenerated" "$TMP") || true)
    if [[ -n "$diff_out" ]]; then
        echo "docs/MAP.md is stale. Run: scripts/gen_map.sh" >&2
        exit 1
    fi
    echo "docs/MAP.md is up to date."
else
    mv "$TMP" "$OUT"
    trap - EXIT
    echo "Wrote $OUT"
fi
